import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import StyledJsxRegistry from '../../registry';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core';
config.autoAddCss = false;

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Do Blogging',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <StyledJsxRegistry>
                <body className={inter.className}>
                    <Navbar />
                    <div className="main-container flex justify-center items-center relative">
                        {children}
                    </div>
                    <Footer />
                </body>
            </StyledJsxRegistry>
        </html>
    );
}
